services:
  localstack:
    container_name: s3_iam
    image: localstack/localstack
    ports:                      
      - "4566:4566"                       
      - "0.0.0.0:4510-4559:4510-4559"     
    environment:
      - S3_SKIP_SIGNATURE_VALIDATION=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME=localhost
      - DEBUG=1
      - SERVICES=s3,iam,dynamodb                   
    volumes:
      - "s3_volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"  
    networks:
      - localstack_network

  cli:
    container_name: aws_cli
    image: amazon/aws-cli
    stdin_open: true                       
    tty: true                              
    entrypoint: /bin/bash                  
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
    networks:
      - localstack_network
    depends_on:
      - localstack 

networks:
  localstack_network:
    driver: bridge 

volumes:
  s3_volume:       
