services:
  localstack:
    container_name: dynamo_iam
    image: localstack/localstack
    ports:                      
      - "4566:4566"                       
      - "0.0.0.0:4510-4559:4510-4559"
      - "8080:8080"     
    environment:
      - HOSTNAME=localhost
      - PORT_WEB_UI=8080
      - SERVICES=iam,dynamodb     
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}           
    volumes:
      - "dynamo_vol:/var/lib/localstack"
    networks:
      - localstack_network
 

networks:
  localstack_network:
    driver: bridge 

volumes:
  dynamo_vol:       
